# Generated by Django 4.2.30 on 2026-07-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_content_format_lessoncomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='attachment',
        ),
    ]
